includes/core/classes/class-setup.php

This PR adds a link to GatherPress settings on the plugins page, which quickly distinguishes where users are expected to make changes to plugin settings.

Add Settings signpost to Plugin Actions

---

includes/core/classes/class-event.php
test/unit/php/includes/core/classes/class-test-event.php

* Adds an offset option to `has_event_started`, `has_event_past` methods, and `is_event_happening` methods. 
* Updated call to `is_event_happening` method to have a `-5` (minute) offset when enabling an online event link.
* Update unit tests to test offsets.

Added offset to event started and event past methods.

---

includes/core/classes/class-event.php
test/unit/php/includes/core/classes/class-test-event.php

PR https://github.com/GatherPress/gatherpress/pull/508 was reverted due to bug not invalidating cache on update. This PR replaces cache with transient API so DB calls aren't repeated.
Closes #507 
Functionality around datetime should remain same. Use Query Monitor to see no more repeated calls to `get_datetime` method, which resulted in duplicated DB calls.
Props @mauteri, @deshabhishek007

Add caching of datetimes to improve performance.

---

includes/templates/admin/settings/index.php

GatherPress Settings page was not showing `Settings saved.` or any kind of message after saving. This change adds that messaging.
Closes #510 
Go to Events -> Settings and save. Message will appear now.
N/A
Props @mauteri

Added settings_errors() to GatherPress settings template.

---

includes/core/classes/class-rsvp.php

Bug with guest settings. Should use meta not global for number of guests check.
Closes #574 
Props @mauteri

Fix bug with guest settings.

---

includes/core/classes/class-event.php
includes/core/classes/class-user.php

Decouples and adds filters for better manageability.
Closes #577 
Make sure date/time/timezone users settings are still functioning as expected.
Props @linusx

decouple and user filters

---

.github/workflows/wordpress-version-checker.yml

Currently, the *WordPress version checker* workflow runs on every PR, even when made from outside the *GatherPress* organization.
I'd like to prevent this workflow to run on forks outside of the GatherPress organization, because the required permission to create an issue would not be given and the workflow would fail.
Using a condition check, to test for the *GatherPress* org will skip the test for every PR, that is opened from an external namespace.
~~Closes #~~
1. Fork GatherPress into your namespace
2. Create a new branch, commit and publish some changes
3. open a PR to merge your new branch into the `main` branch 
4. See the workflow to be skipped, [like I did](https://github.com/carstingaxion/gatherpress/pull/11#issuecomment-1981876745).
> Changed - Prevent the *WordPress version …

Skip the version-checker-workflow outside of GatherPress org

---

includes/core/classes/class-assets.php
test/unit/php/includes/core/classes/class-test-assets.php

Fixes issue with endless calls to admin ajax due to erroneous self-closing div tag in FireFox.
Closes #605 
See issue it closes, that should not happen anymore. This issue only happens in FireFox, not Chrome.
Props @carstingaxion, @mauteri

Fix markup issue with self-closing div tag.

---

includes/core/classes/class-event-query.php
includes/core/classes/class-event.php
includes/core/classes/class-rsvp.php
test/unit/php/includes/core/classes/class-test-event-query.php

In WP 6.2 the %i placeholder was made available for table or field names in a prepare statement. This change utilizes that feature to improve SQL calls.
Closes #614
All queries should remain same.
Props @mauteri

Fix SQL calls with %i placeholder

---

src/components/Rsvp.js

This is follow-up to #633, because I wanted to start without the reverted commits.
I described in [a comment on the old PR](https://github.com/GatherPress/gatherpress/pull/633#issuecomment-2028942164) more in details what happened.
Closes #623 
1. Make sure you are not logged
2. Click RSVP button to RSVP to an event.
3. Login modal pops up with working Links for Login and Registration.
> Fixed - Bug fix missing text in RSVP modal
Props @jmarx, @carstingaxion

Wrap strings in backticks to make sprintf work

---

includes/core/classes/class-user.php

Sanitize nonce check.
Closes #611 
Props @mauteri

Sanitize nonce check.

---

includes/core/classes/class-event.php
test/unit/php/includes/core/classes/class-test-event.php

Bug was introduced when we removed the `is_event_happening` check, which made the event active when it started. Issue is that it never went inactive after the event ended. Updated code and added unit test for this.
Closes #
Props @mauteri

Fix event in past link issue.

---

includes/core/classes/class-venue.php

Sets rewrite to false when registering venue shadow taxonomy.
Closes #676 
Props @mauteri, @carstingaxion

Fix public requests of shadow venue taxonomy.

---

includes/core/classes/class-setup.php
readme.md
test/unit/php/includes/core/classes/class-test-setup.php

Fix multisite activation

---

includes/core/classes/class-venue.php
test/unit/php/includes/core/classes/class-test-venue.php

Closes #730
> Fixed - The terms of the shadow taxonomy `_gatherpress_venue` were not deleted, when the corresponding `gatherpress_venue` posts were deleted
Props @carstingaxion, @mauteri

Reflect changes to the venue term, when a venue post gets deleted.

---

includes/core/classes/class-autoloader.php

Changes to autoloader to allow companion plugins to register and utilize the autoloader via the `gatherpress_autoloader` filter. This filter is an array where the key is the namespace (eg `GatherPress`) and the value is the root directory (eg `__DIR__`).
Everything in GatherPress should work normally.
Props @mauteri

Updates to autoloader.

---

.github/workflows/jest-tests.yml
.github/workflows/phpunit-tests.yml
.github/workflows/playground-preview.yml

Restrict the GitHub action workflows to run only if the containing PR includes changes to relevant files.
~~Closes #~~
...
> Changed - Restrict the GitHub action workflows to relevant file changes.

Restrict workflow-runs to run only for necessary files

---

includes/core/classes/class-setup.php

~~Closes #~~ Follow-up Bug fix for #739
> Fixed - Fix alpha-admin-notice to not render into REST requests, etc.

Fix admin-Notice to not render into REST requests, etc.

---

.github/workflows/playground-preview.yml

I'm looking for the playground preview once again. And I need the workflow to be in the repo first, like I described in the original PR, but missed an important aspect, that should be fixed with the new trigger `pull_request_target`, which I introduce with this PR.
~~Closes #~~ Follow-up bug-fix for #666 & #741

TRY Fixing the playground-preview for outside collaborators.

---

includes/core/classes/class-utility.php

Closes #746
1. Have English selected in Settings > General as Site language.
2. Edit your user profile, choose a different language for your user and save!
3. See the main admin menu changed into your users language.
4. Go to Plugins and toggle the activation of the plugin on and off.
A. Plugin not activated: Admin Bar is translated into your users language
B. Plugin activated: Admin Bar is NOT translated, shows in English
1. Have English selected in Settings > General as Site language.
2. Edit your user profile, choose a different language for your user and save!
3. See the main admin menu changed into your users language.
4. Go to Plugins and toggle the activation of the plugin on and off.
A. Plugin not activated: Admin Bar is translated into your users language
B. Plugin activated: …

Respect users locale

---

.github/scripts/create-preview-links.js
.github/workflows/playground-preview.yml

This PR adds some minor enhancements to the - now almost, almost, almost ready - Pull request playground previews:
- Run the time & ressource intensive build-step only if the changed files require that really
- Set “Add a new event post” as landing page for the playgrounds
- Set php version to 8.2 and wp version to latest
- Run in network mode (to allow the download of additional plugins or themes)
- Setup as WordPress Multisite 
~~Closes #~~ Testing & Clean-up after #666 & #741
> Changed - …

Enhance playground PR previews 

---

.github/workflows/playground-preview.yml

When the playground-preview workflow is triggered and never will run the `build` step, because all changes were made to other (than the workflow triggering) files, nothing is uploaded as artifact and so the `comment` step would output a non-working playground link.
This PR makes sure the `build` step runs at least once, when the PR is opened. 
~~Closes #~~ Testing & Clean-up after #666, #741, #749 & #750
1. Test that it NOT runs
1. Open a PR
2. ...with changes to `.github/...` or `.wordpress-org/...`
3. See that the whole workflow is NOT triggered.
2. Test that it runs _1/2_
1. Open a PR
2. ... with changes to `src/...`
3. See that the workflow is triggered & the `build` step runs succesfully.
3. Test that it runs _2/2_
1. Open a PR
2. ... with changes to `includes/...`
3. See that the …

Make sure the build step runs at least once, when the PR is opened.

---

.github/workflows/coding-standards.yml

Fix StyleLint name.

---

includes/data/credits.php
readme.md

Add Carsten as lead.

---

.github/workflows/playground-preview.yml

Revert additional step from the Playground preview workflow, that was meant to restrict the workflow runs to the only necessary ones. Now the workflow is back to its former overall-strategy that triggers on every change to:
- 'build/**'
- 'includes/**'
- 'src/**'
- '*.php'
Thanks to @mauteri for helping out on this [via slack](https://gatherpress.slack.com/archives/C010M3FV65V/p1723325499181499?thread_ts=1722435789.874679&channel=C010M3FV65V&message_ts=1723325499.181499).
~~Closes #~~ Testing & Clean-up after #666, #741, #749, #750, #753 & #757
> ### [How to test the Change](https://github.com/GatherPress/gatherpress/pull/753)
> 
>     1. Test that it NOT runs
>        
>        1. Open a PR
>        2. ...with changes to `.github/...` or `.wordpress-org/...`
>        3. See that the …

Cleanup workflow from un-thought code

---

.distignore
includes/core/classes/class-export.php
includes/core/classes/class-import.php
includes/core/classes/class-migrate.php
test/unit/php/includes/core/classes/class-test-export.php
test/unit/php/includes/core/classes/class-test-import.php
test/unit/php/includes/core/classes/class-test-migrate.php

Added unit tests and small code cleanup.

---

.github/workflows/playground-preview.yml
gatherpress.php

Fix ref, to checkout before build, to point to the latest PR commit, not the latest commit of the main branch.
~~Closes #~~ Testing & Clean-up after #666, #741, #749, #750, #753, #757 & #770

Run Playground Preview build against latest PR, not latest main

---

includes/core/classes/class-setup.php

~~Closes #~~
> Changed - Show admin notices only in relevant spots, but also in multisite admin.

Show admin_notices only in relevant spots & also in multisite admin

---

.github/workflows/dependency-review.yml

Following the description at https://github.com/actions/dependency-review-action/issues/809#issuecomment-2285930024
> Version 4.3.4 does not work with invalid license names in the config and since that version,
SPDX expression licenses are considered invalid (see: https://github.com/actions/dependency-review-action/issues/792).
>
>In short, remove all SPDX expressions from the config!
Note that if you have packages that use SPDX expressions, this will report them as invalid,
as support is not yet implemented (see: https://github.com/actions/dependency-review-action/issues/263).
>
>In that case you need to downgrade to version 4.3.3 where SPDX expressions are handled as exact strings !!
~~Closes #~~ Hopefully fixes the [failing GitHub workflow …

Downgrade dependency-review-action to version 4.3.3

---

includes/core/classes/class-setup.php

While a plugin from w.org would have a unigue slug to check against,
this is different for .zips downloaded from github.com.
A download via "<> Code ⏷" > "Download ZIP" will include the branch in the file name,
while a download via "Releases" will provide a zip without a branch name attached.
This PR makes sure, that GatherPress checks against both possible slugs inside the condition to whether or not to show the admin notice about the alpha-plugin.
Closes #807
> Fixed - Hide Admin Notice about alpha-plugin, also if installed via the branch-named zip

Hide Admin Notice about alpha-plugin, also if installed via the branch-named zip

---

gatherpress.php
includes/data/credits.php
package-lock.json
package.json
readme.md

Just updates version to 0.31.0-alpha
Closes #

Starting 0.31.0-alpha.

---

.wordpress-org/blueprints/blueprint.json

Use 'modern' Admin-UI in w.org Playground

---

includes/core/classes/class-event.php

Closes #635
> Changed - Made `GatherPress\Core\Event`'s `get_formatted_datetime()` and `get_calendar_description()` methods public (from protected).
Props @JordanPak

Make `Event->get_formatted_datetime()` method public

---

docs/user/2-gatherpress-settings.md
includes/core/classes/settings/class-general.php
src/components/OpenStreetMap.js

This commit replaces all instances of "Open Street Maps" with "OpenStreetMap" in the code and documentation.
Fixes #833
This change corrects the name "Open Street Maps" to "OpenStreetMap" throughout the GatherPress codebase, including documentation and map configuration settings.
The reason for this change is discussed in issue #833, where it's noted that the correct name is "OpenStreetMap."
1. Open any event in the GatherPress plugin that uses map settings.
2. Verify that "OpenStreetMap" is displayed as the mapping provider option.
3. Check the documentation for the correct mention of "OpenStreetMap."
> Fixed - Corrected the name "Open Street Maps" to "OpenStreetMap" across the project.
Props @matt-galdino.

Replace "Open Street Maps" with "OpenStreetMap"

---

.github/scripts/wordpress-org-screenshots/wporg.spec.ts
readme.md

I wanted to do something _nice_, _something visually appealing_.
... so I updated the screenshot generator to use the latest demo-data event as prominent example in screenshots ;)
https://github.com/user-attachments/assets/f4e7ce3e-2944-45b6-abc8-858d9254117d
~~Closes #~~
> Changed - Use latest demo-data event as prominent example in screenshots

Use latest demo-data event as prominent example in screenshots

---

includes/core/classes/class-event-query.php
includes/core/classes/class-settings.php
phpcs.ruleset.xml

I stumbled upon this error
```sh
FILE: includes/core/classes/class-event-query.php
-----------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
-----------------------------------------------------------------------------------------------------------------------------------------------------------
343 | ERROR | The %i modifier is only supported in WP 6.2 or higher. Found: "%i". (WordPress.DB.PreparedSQLPlaceholders.UnsupportedIdentifierPlaceholder)
345 | ERROR | The %i modifier is only supported in WP 6.2 or higher. Found: "%i". (WordPress.DB.PreparedSQLPlaceholders.UnsupportedIdentifierPlaceholder)
---
```
after I removed a  `// phpcs:ignore ...` statement for …

Fix & update phpcs rules

---

includes/templates/admin/emails/event-email.php

Fragmentation of #752
Until this PR GatherPress sends email including an img-tag, even if the event has no featured-image set.
~~Closes #~~
Send yourself an event-email, that has no image set and prove that thze received email doesn't contain an empty img-tag.
> Fixed - Conditionally render the featured image in the email, only if it is set.

Conditionally render the featured image in the email, only if it is set.

---

includes/templates/admin/emails/event-email.php

Fragmentation of #752
Until this PR GatherPress sends email with a fixed language attribute of "en-us", which doesn't reflect the sites or users locale.
~~Closes #~~
1. Change your sites default language to anything else, than en_US.
2. Send yourself an email via an event
3. Check the html of the sent email for the lang-attribute on the html element.
4. This should reflect your set language
> Fixed - Set html language attributes correctly for emails

Set html language attributes correctly for emails

---

includes/core/classes/class-user.php

Fragmentation of #752
---
In the gatherpress timeformat settings, `\` are ok and allowed.
While within the `profile.php`, they are not and get stripped off on save.
This PR fixes that and allows to enter & save special chars into the custom datetime formatting settings.
~~Closes #~~
Try to save the German timeformat and check it is actually saved: `G:i \U\h\r`,
which is the same as saying _`G:i o'clock`_
> Fixed - Allow special chars in user-defined date- and time-format strings

Allow special chars in user-defined date- and time-format strings

---

includes/core/classes/class-event-rest-api.php

Fragmentation of #752
Until this PR, sent emails dont respect the users locale nor her personal date- and time formatting settings.
This PR fixes that, by:
- Loading the users locale before sending emails & resetting it afterwards
- Set the _current user_ to the actual member to mail to, to make sure the GatherPress filters for date- and time- format, as well as the users timezone, are recognized by the functions inside `render_template()`
~~Closes #~~
Testing this PR might be a little tricky and is not possible with WordPress Playground because of the necessary sending & receiving of emails.
1. Setup at least two different users
2. One of the users creates an event, the other users attends. _(This will make sure, 2 emails are sent for the test)_
3. Assign a non-site-default language to …

Respect users locale and custom date- and time-formats in sent emails

---

.distignore
.github/workflows/phpstan-tests.yml
.gitignore
composer.json
composer.lock
gatherpress.php
includes/core/classes/class-assets.php
includes/core/classes/class-event-query.php
includes/core/classes/class-event-rest-api.php
includes/core/classes/class-event-setup.php
includes/core/classes/class-event.php
includes/core/classes/class-export.php
includes/core/classes/class-import.php
includes/core/classes/class-rsvp-query.php
includes/core/classes/class-rsvp-setup.php
includes/core/classes/class-rsvp.php
includes/core/classes/class-settings.php
includes/core/classes/class-setup.php
includes/core/classes/class-venue.php
includes/core/classes/traits/class-singleton.php
includes/core/requirements-check.php
includes/templates/admin/settings/fields/select.php
phpstan.neon.dist
phpstan.stubs
test/unit/php/includes/core/classes/class-test-event-query.php
test/unit/php/includes/core/classes/class-test-event-rest-api.php
test/unit/php/includes/core/classes/class-test-rsvp.php
test/unit/php/includes/core/classes/class-test-settings.php

>#### WordPress extensions for PHPStan
>
>Static analysis for the WordPress ecosystem.
>
>https://github.com/szepeviktor/phpstan-wordpress
This PR introduces a new GitHub action workflow to run PHPStan incl. *the* WordPress extension. 
On behalf of this static analysis I fixed a lot of little problems. While most of the fixes are simple & self-explanatory, the following 6/36 fixes may need a second pair of eyes:
- https://github.com/GatherPress/gatherpress/pull/931/commits/684d1ec78fbe3cc62ac84da98a69b5aca1076e71
- https://github.com/GatherPress/gatherpress/pull/931/commits/3242163db44d281b8ca2ca1806d4af952c7910ae
- https://github.com/GatherPress/gatherpress/pull/931/commits/33fcfeb46992657ce8d88b5d64c3c8a8fd79f116
- https://github.com/GatherPress/gatherpress/pull/931/commits/0ad3a3e80cb76 …

NEW action PHPStan & 36 little :bug: fixes

---

phpstan.neon.dist
phpstan.stubs

After #931 was merged, I realized, that GatherPress could still benefit from type checking for the ignored, not-loaded constants.
Instead of ignoring, I created stubs, that provide at least the type of data.
~~Closes #~~
```bash
composer test:phpstan
```
> Fixed - phpstan: Use stubs, instead of ignoring

Fix phpstan: Use stubs, instead of ignoring

---

docs/contributor/unit-tests/README.md
docs/developer/README.md

This PR is part of the fragmentation of #831, which was way too big to review or merge.
*I try to do better in the future.*
This PR adds:
1. NEW docs about unit tests 
2. a small fix for the default port number of wp-env
3. a new script entry to auto-lint markdown errors
~~Closes #~~
1. _RTFM_
> Added - New developer documentation about unit testing GatherPress

new calendar endpoints | part 1/n | docs unittests

---

gatherpress.php
includes/data/credits.php
package-lock.json
package.json
readme.md

Updated to version 0.32.0-alpha.2.

---

includes/core/classes/class-rsvp-setup.php
includes/core/classes/class-rsvp.php
test/unit/php/includes/core/classes/class-test-rsvp-setup.php

Fix waiting list check when max limit is 0 meaning it has no limit.

---

test/unit/php/includes/core/classes/blocks/class-test-dropdown-item.php

Added unit tests for Dropdown_Item block class.

---

test/unit/php/includes/core/classes/class-test-validate.php

Added unit test coverage for Validate class.

---

test/unit/php/includes/core/classes/blocks/class-test-dropdown.php
test/unit/php/includes/core/classes/blocks/class-test-general-block.php

Added tests for General_Block class.

---

includes/core/classes/blocks/class-rsvp-template.php
includes/core/classes/class-assets.php

This fixes #1076 by adding a `! empty()` check. And #1047 by checking if the given array has the key we want to check.
Also replaced `strpos()` with `str_contains()` as it is available as polyfill since WordPress 5.x
Closes #1076
Closes #1047 
Open a topic listing with WP_DEBUG active.
> Fixed - Deprecated: json_decode(): Passing null to parameter #1 ($json) of type string is deprecated
> Fixed - Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated
Props @apermo, @shawfactor

Fix deprecations

---

includes/core/classes/blocks/class-modal-manager.php
src/blocks/dropdown/view.js
src/blocks/modal-manager/view.js
src/blocks/rsvp/view.js

Gen Herres was kind enough to review the accessibility with me in of our new blocks that were reworked in 0.32.0. While they were improved, some issues were still discovered.
- After clicking escape, close, or clicking outside the modal which closes it, focus should return to the button that original opened the modal. Right now, focus is lost.
- After clicking "Attending," the modal does not close (which is correct), however, focus should be on "Close" as that's the next logical step (if close button exists).
- In addition, I fixed escape on dropdown to return to the triggering element.
Closes #1041
Props @mauteri

Improve and fix accessibility issues in modal and dropdown blocks.

---

gatherpress.php
includes/core/duplicate-check.php

…
https://github.com/orgs/GatherPress/projects/1/views/1?pane=issue&itemId=107988139&issue=GatherPress%7Cgatherpress%7C1071
Closes GP-1071
Try to activate 2 different versions of GP at the same time and you will see an activation error message
> Added - new check to search for other instances of GP installation
@stephenerdelyi

Added a new check to determine if gatherpress has already been installed/activated

---

.distignore

While looking at https://plugins.trac.wordpress.org/browser/gatherpress/#tags/0.32.2 and https://plugins.trac.wordpress.org/browser/gatherpress/trunk I noticed that you've included the `.wordpress-org` directory in the released versions of the plugin, although this is intended to be the `assets/` folder only.
See https://github.com/10up/action-wordpress-plugin-deploy?tab=readme-ov-file#excluding-files-from-deployment
Fixed - smaller release ZIPs as we no longer ship the screenshots as part of the release.

Don't include the .wordpress-org directory in the released versions of the plugin

---

.wp-env.json

Adds schema to `wp-env` config JSON.
Check the branch out and see if your code editor will auto-complete props in `.wp-env.json`.
@JordanPak

Add `$schema` prop to `wp-env` config

---

.gitignore

Adds root `mu-plugins` to the gitignore so contributors can conveniently map some local `mu-plugins`.
1. Create a `.wp-env.override.json` with
```
{
"$schema": "https://schemas.wp.org/trunk/wp-env.json",
"mappings": {
"wp-content/mu-plugins": "./mu-plugins"
}
}
```
2. Make a `mu-plugins` directory in the root and throw a drop-in plugin in there.
3. The plugin should load after restarting the WordPress environment, and it won't be tracked in the repo.
> Changed - Add `mu-plugins/` to `.gitignore` for `mappings` in potential `.wp-env.override.json`
@JordanPak

Add `mu-plugins` to `.gitignore` (for `.wp-env.override.json` mapping)

---

includes/core/classes/blocks/class-event-query.php
includes/core/classes/class-event-query.php
includes/core/classes/class-feed.php
src/variations/core/query/components.js
src/variations/core/query/controls.js
src/variations/core/query/index.js
test/unit/php/includes/tests/core/classes/class-test-event-query.php
test/unit/php/includes/tests/core/classes/class-test-feed.php

Closes #1188
**Test the past events feed:**
Visit http://yoursite.com/event/feed/?type=past - should show past events
Visit http://yoursite.com/event/feed/ - should show upcoming events
**Test the automatic feed link on past events page:**
Configure a past events archive page in GatherPress Settings
Visit that page and check the RSS feed link in page source
Verify the link includes ?type=past parameter
Test edge cases:
?type=invalid should default to upcoming events
?type= should default to upcoming events
Adds support for past events RSS feeds via ?type=past parameter. When viewing the past events archive page, the RSS feed link automatically includes this parameter.
Added - Past events RSS feed support with ?type=past parameter
Props @jmarx

Past events feed
