core/classes/class-settings.php, gatherpress.php
=> Move GP Settings under Events Admin Menu

core/classes/class-settings.php, gatherpress.php
Fix for php8 requirement to have integer, not boolean for comparisons.
=> PHP8 wants integer, not boolean

core/classes/class-setup.php
This PR removes the restriction forcing a unique permalink that appends postID to existing.
=> Remove restrictions on permalinks

tests/includes/core/classes/class-test-venue.php
100% for https://github.com/GatherPress/gatherpress/blob/main/includes/core/classes/class-venue.php#L185
=> WIP: Unit test get_venue_meta method

playwright.config.js
Updated test retries value 2 for CI and local environments
=> config: set retries to 2 for playwright tests

README.md
Please check my English :)
To be added:
- wp.org links for Prashant and Prayag
- other team members?
- link to the demo video on the website's future documentation page
=> Add user documentation to readme

test/unit/php/includes/core/classes/class-test-rsvp.php
Test sometimes fails because it checks RSVP status before it has a moment to be updated.
Closes #515 
Test should not fail any longer.
N/A
Props @mauteri
=> Added slight delay for occasionally failing test.

includes/core/classes/class-rest-api.php, includes/core/classes/class-setup.php, includes/core/classes/class-user.php, includes/templates/admin/user/notifications.php, test/unit/php/includes/core/classes/class-test-assets.php, test/unit/php/includes/core/classes/class-test-block.php, test/unit/php/includes/core/classes/class-test-event.php, test/unit/php/includes/core/classes/class-test-rest-api.php, test/unit/php/includes/core/classes/class-test-rsvp.php, test/unit/php/includes/core/classes/class-test-setup.php, test/unit/php/includes/core/classes/class-test-user.php, test/unit/php/includes/core/classes/class-test-utility.php, test/unit/php/includes/core/classes/class-test-venue.php, test/unit/php/includes/core/classes/commands/class-test-cli-event.php
This adds an important privacy feature where users can opt-in or opt-out of message sent by organizers about upcoming events.
Closes #514 
N/A
Props @mauteri
=> Checkbox in user profile to opt-in or out to event email notifications.

includes/core/classes/settings/class-general.php
=> Set anonymous rsvp to false by default.

includes/templates/admin/user/notifications.php, test/unit/php/includes/core/classes/class-test-event.php, test/unit/php/includes/core/classes/class-test-rsvp.php
=> Cleaned up sonarcloud issue and added unit tests.

includes/data/credits/credits.php, includes/data/credits/latest.php
=> Move Patricia to project leadership.

README.md
- changed Documentation > features to add Anonymous RSVP
- added credits to reflect contributors as in includes/data/credits/credits.php
Changed - README.me Documentation > Features
=> Update README for 0.28.0

includes/data/credits/credits.php, includes/data/credits/latest.php
=> Update credits to include Carsten Bach.

includes/data/credits/credits.php
=> Add steve to team.

includes/core/classes/class-setup.php
The PR ensures the plugins textdomain is set up and loaded, before everything else (on the `init` hook) is loaded.
I slightly decreased the priority to let the textdomain registration happen already on `init:9`, rather than on `10`, which is the used default throughout the rest of GatherPress.
https://github.com/GatherPress/gatherpress/blob/main/includes/core/classes/class-setup.php#L82
I've had some hard times to debug, why only *some* of the existing translations where loaded at a time, but - unfortunately - I haven't opened an issue, yet. So ... this ~~Closes #~~ 
1. Use version 0.28.0
2. Change your sites locale to DE, FR, or ES.
3. You can see, some parts of the GatherPress UI is translated, some not. For example the main menu-items, which occur in english, while 90% of the …
=> Make sure textdomain is loaded before registering post_types etc.

includes/core/classes/class-cli.php, includes/core/classes/class-utility.php, includes/core/classes/class-venue.php, includes/core/classes/commands/class-develop-cli.php, includes/core/classes/commands/class-event-cli.php, test/unit/php/includes/core/classes/class-test-rsvp.php, test/unit/php/includes/core/classes/class-test-utility.php, test/unit/php/includes/core/classes/commands/class-test-event-cli.php
=> Code clean up and new tests.

readme.md
=> Add to and update readme.md.

readme.md
Add new demo video to Readme.md, with image placeholder stored on gatherpress.org and linked to the current demo via the Prettylink plugin
Closes #
=> Add new demo video to readme.md

gatherpress.php, includes/data/credits/credits.php, includes/data/credits/latest.php, package-lock.json, package.json, readme.md
=> Update version to 0.30.0-alpha

build/admin_style.css, includes/core/classes/class-setup.php, includes/templates/admin/setup/membership-check.php, includes/templates/admin/setup/site-check.php, languages/gatherpress-ca.po, languages/gatherpress-de_AT.po, languages/gatherpress-de_CH.po, languages/gatherpress-de_CH_informal.po, languages/gatherpress-de_DE.po, languages/gatherpress-de_DE_formal.po, languages/gatherpress-es_ES.po, languages/gatherpress-fr_FR.po, languages/gatherpress.pot, src/admin.scss, test/unit/php/includes/core/classes/class-test-setup.php
=> Update membership-check.php to include timezone check

includes/core/classes/class-venue.php
Make correct change.
Closes #
Props @mauteri, @carstingaxion
=> Change from rewrite false to publicly_queryable false.

includes/core/classes/class-setup.php, readme.md, test/unit/php/includes/core/classes/class-test-setup.php
Installing GatherPress on a WordPress multisite was not activating correctly.
* Tables were not being created when the plugin activated.
* Tables were not created when a new site was added to the network.
This PR fixes both of those issues and refactors code a little bit.
Activate the plugin in a multisite network and GatherPress custom tables for events and rsvp should be created for each site. Add a new site to the network and tables should be created.
Props @mauteri @patriciabt
=> Fix table creation issue on multisite.

includes/core/classes/class-venue.php
https://github.com/GatherPress/gatherpress/assets/198883/dfc4dba8-2f6b-47a3-942c-6bb7779157b6
Closes #670 
> Added - Allow to filter events in admin list table by venue
=> Allow to filter events in admin list table by venue

includes/core/classes/commands/class-develop-cli.php, includes/data/credits/latest.php
=> Update CLI per wp.org

build/blocks/online-event/render.php, src/blocks/online-event/render.php
=> Fix last render issue.

build/blocks/add-to-calendar/render.php, build/blocks/event-date/render.php, build/blocks/events-list/render.php, build/blocks/online-event/render.php, build/blocks/rsvp-response/render.php, build/blocks/rsvp/render.php, build/blocks/venue/render.php, includes/core/classes/commands/class-develop-cli.php, includes/data/credits/credits.php, includes/data/credits/latest.php, src/blocks/add-to-calendar/render.php, src/blocks/event-date/render.php, src/blocks/events-list/render.php, src/blocks/online-event/render.php, src/blocks/rsvp-response/render.php, src/blocks/rsvp/render.php, src/blocks/venue/render.php
=> Move changes from 0.29.3 release to main branch.

test/e2e/admin-tests/gatherpress-event-loggedIn.spec.js, test/e2e/admin-tests/gatherpress-event-nonLoggegIn.spec.js, test/e2e/admin-tests/gatherpress-event.spec.js, test/e2e/reusable-user-steps/user-login.js
Test descriptions:
1. the user should for publish the online event
2. the user should for publish the offline event
3. verify the logged in user view RSVP button on home page and perform RSVP action
4. verify the non-logged in user view RSVP button on home page and perform RSVP action
> Added - New tests for event functionality
@prashantabellad , @01Prayag
=> test scripts for event scenarios

test/e2e/admin-tests/gatherpress-event-loggedIn.spec.js, test/e2e/admin-tests/gatherpress-event-nonLoggegIn.spec.js, test/e2e/admin-tests/gatherpress-event.spec.js
updated the event test functionality tests
=> update the event functionality tests

.github/workflows/wordpress-org-plugin-guidelines.yml
The Plugin Check GitHub Action is now part of the WordPress GitHub organization. This PR reflects that.
Check should still pass.
> Changed - Adjusted GitHub Action name in workflow file
Props @swissspidy
=> Update name of Plugin Check action

includes/data/credits.php
=> Add Pascal Birchler credit.

includes/core/classes/class-event.php, test/unit/php/includes/core/classes/class-test-event.php
https://github.com/GatherPress/gatherpress/assets/198883/7d930ae0-7ea7-4fa9-952b-899ca4333471
Closes #724 
1. Create an event with an ampersand (for example) in the title
2. Publish and view event.
3. Choose any of the 'Add to calendar' options and open the new event in your calendar
4. See that everything behind the special character is ~~missing~~ in place.
> Fixed -  "Add to calendar" links not working for events with special charcters in title, description or venue
=> Add URL encoding to 'Add to calendar' links

includes/core/classes/class-setup.php, includes/templates/admin/setup/gatherpress-alpha-check.php
This change adds an admin notice when the GatherPress Alpha plugin isn't installed/activated. This will link to the GitHub repo to download GatherPress Alpha. The readme file in GatherPress Alpha will be updated next for detailed instructions for installing the plugin.
Closes #737 
See the notice appear if GatherPress Alpha is not installed. It will not appear if it is.
Props @mauteri
=> GP-737: Add GatherPress Alpha warning.

.github/scripts/create-preview-links.js, .github/workflows/playground-preview.yml
Follow-up for https://github.com/GatherPress/gatherpress/pull/666 to finalise the Playground pull request previews.
...
...
=> Finetuning for the playground pull request preview

.distignore
readme.md should not be in distignore.
Closes #
Props @mauteri @swissspidy
=> Remove readme.md from distignore.

.github/workflows/playground-preview.yml
Hopefully fixes https://github.com/GatherPress/gatherpress/actions/runs/10223043895
~~Closes #~~ Testing & Clean-up after https://github.com/GatherPress/gatherpress/pull/666, https://github.com/GatherPress/gatherpress/pull/741, https://github.com/GatherPress/gatherpress/pull/749, https://github.com/GatherPress/gatherpress/pull/750, https://github.com/GatherPress/gatherpress/pull/753 & #757 
> Fixed - Bug fix invalid workflow file
=> Remove "Unexpected symbol" resulting in "The workflow is not valid." error

.distignore
=> Remove .wordpress-org from distignore.

.github/scripts/create-preview-links.js, .wordpress-org/blueprints/blueprint.json
Closes #649, Closes #663
> Changed - Update URLs to demo-data repo to use GatherPress namespace
=> Update URLs to demo-data repo to use GatherPress namespace

docs/user/1-install-gatherpress.md, docs/user/1a-gatherpress-alpha.md, docs/user/2-gatherpress-settings.md, docs/user/3-create-or-edit-a-venue.md, docs/user/4-gatherpress-topics.md, docs/user/5-create-or-edit-an-event.md
Closes #780
> Changed - Updated documentation as per #780 discussion - added further content and background of settings screen options.
=> Updated Documentation Pages

docs/user/3-create-or-edit-a-venue.md, docs/user/4-gatherpress-topics.md, docs/user/5-create-or-edit-an-event.md
We made the user documentation with Steve, and did some corrections.
Thank you so much Steve, props  @malgrauk for this team work :)
=> Corrections to user documentation

includes/core/classes/class-venue.php
=> Fix venues label.

includes/core/classes/class-venue.php
=> Fix venue context.

gatherpress.php, includes/data/credits.php, package-lock.json, package.json, readme.md
=> Preparing release of 0.30.0.

.github/workflows/wordpress-org-readme-md-validation.yml, readme.md
This PR introduces a [new README validation workflow](https://github.com/marketplace/actions/wordpress-plugin-readme-md-validator) and a subtle fix to the existing readme.
> A GitHub Action that validates that the heading section of your plugin's README.md has newlines handled correctly.
>
> When writing markdown, two spaces are required at the end of a line to preserve single line breaks in the rendered view. Some people's (@jazzsequence) IDEs helpfully remove these and the diff can be missed in GitHub's PR view.
I had the feeling, that the readme.md is rendered weird on GitHub, so I looked for a validation and found this action.
The screenshots proofed my unclear feeling.
| BEFORE | AFTER |
|--------|--------|
| ![IMG_0209](https://github.com/user-attachments/assets/50e389fb-99a8-4ef7-9a …
=> NEW workflow: WordPress.org README.md validation

.github/workflows/dependency-review.yml
=> Try to fix GH action issue.

.github/workflows/dependency-review.yml
=> Revert but fix typo.

.github/workflows/dependency-review.yml
Removes the `push` event from the list of triggers to start the **dependency-review workflow**, as it was before #777.
Closes https://gatherpress.slack.com/archives/C010M3FV65V/p1724630783751909?thread_ts=1724621668.219139&cid=C010M3FV65V
> Fixed - Failing dependency review workflow
=> Remove push from workflow triggers (which was set by accident in #777)

.github/workflows/wordpress-org-screenshots.yml
This is a small follow-up on #838 to make the selectable option of the workflow a Boolean. Having this as a string makes no sense.
~~Closes #~~
> Fixed - Workflow input to be a bool option.
=> Make ‚Update all Screenshots’ a boolean workflow option

.github/workflows/compress-images.yml
=> Fix branch name of compress-image action

.github/workflows/wordpress-org-screenshots.yml
=> Minor fixes

.github/scripts/wordpress-org-screenshots/blueprint.json, .github/workflows/compress-images.yml, .github/workflows/wordpress-org-screenshots.yml
=> TRY another trigger to hopefully get 'compress images'  started now.

includes/core/classes/class-event-rest-api.php, includes/core/classes/class-setup.php, test/unit/php/includes/core/classes/class-test-event-rest-api.php
Rename Rest API class to Event Rest API. This class is specific to events and should be named accordingly. If we add new rest endpoints that do not have to do with events it will make sense to add a new API class for those.
Closes #
Props @mauteri
=> Rename REST API to Event REST API.

readme.md
=> Remove duplication readme.md

docs/developer/README.md
> Added - Documentation for running PHPUnit tests via `wp-env`
Props @JordanPak
- ~I have added tests to cover my change.~
- ~All new and existing tests pass.~
=> Add developer docs section for PHPUnit test execution via wp-env

includes/data/credits.php, readme.md
=> Contributor updates for 0.31.0.

.typos.toml
=> Prevent OSM Typos in the future

.github/scripts/create-preview-links.js
=> Use php matrix in playground PR preview

includes/core/classes/class-venue.php, test/unit/php/includes/core/classes/class-test-rsvp.php, test/unit/php/includes/core/classes/class-test-venue.php
=> Added new unit tests, small code changes.

test/unit/php/includes/core/classes/class-test-rsvp.php
=> Mauteri unit test 2

.github/scripts/create-preview-links.js, .github/scripts/wordpress-org-screenshots/blueprint.json, .wordpress-org/blueprints/blueprint.json, docs/contributor/screenshot-generator/README.md
=> Rename demo-data repo

.github/scripts/wordpress-org-screenshots/playwright.config.ts, .github/workflows/wordpress-org-screenshots.yml
=> Fix race-condition during Playground setup and Playwright start

readme.md
> Let’s change the Playground link, it loads the awesome blueprint
>Which seems to be wrong
>
>https://gatherpress.slack.com/archives/C07DZMVL1GX/p1727455902959059
Closes #
=> Fix link to point to the off. blueprint, not the builder with "Awesome"

readme.md
=> Update tested to latest.

.typos.toml, gatherpress.php, includes/data/credits.php, package-lock.json, package.json, readme.md
=> Get ready for 0.31.0

docs/developer/blocks/hookable-patterns/README.md, includes/core/classes/class-block.php, includes/core/classes/class-event-setup.php, includes/core/classes/class-venue.php
After the introduction of hookable block-patterns with #888, this PR updates the post type registration to make use of the new patterns.
All blocks that were previously added to the `template` array, are now added using the [Block Hooks API](https://make.wordpress.org/core/2023/10/15/introducing-block-hooks-for-dynamic-blocks/). This brings a lot of flexibility, which is minimal covered in an updated developer doc.
~~Closes #~~ Follow-up for: #888 (#628)
I provided three examples in the updated [`/docs/developer/blocks/hookable-patterns`](https://github.com/GatherPress/gatherpress/blob/fa5338dadfeea450f406a920885d1111fa8c1355/docs/developer/blocks/hookable-patterns/README.md), which can be used to test.
> Changed - Use hookable-patterns with the existing blocks & update documentation …
=> Use hookable-patterns with existing blocks & DOCS

.github/workflows/sonarcloud.yml
=> Update SonarCloud to include merging to develop.

.github/workflows/wordpress-org-screenshots.yml
=> Add Portuguese (Brazil) locale to screenshot-generator

includes/data/credits.php, readme.md
=> Added Laura Byrne to team.

includes/core/classes/blocks/class-modal-manager.php, includes/core/classes/blocks/class-rsvp.php, includes/core/classes/class-event-rest-api.php
=> a11y updates

includes/core/classes/class-event-setup.php
=> Update event template with V2 blocks for testing.

test/unit/php/includes/core/classes/class-test-event.php
=> Event unit test complete.

includes/core/classes/blocks/class-rsvp.php, test/unit/php/includes/core/classes/blocks/class-test-rsvp.php
=> Started with more unit tests on Rsvp block class.

includes/core/classes/class-rsvp.php
* Record IP address in comments table for RSVPs.
Props @mauteri
=> Save IP address with RSVP.

test/unit/php/includes/tests/core/classes/blocks/class-test-modal-manager.php, test/unit/php/includes/tests/core/classes/blocks/class-test-modal.php
=> Started unit test for Modal.

test/unit/php/includes/tests/core/classes/class-test-event-query.php, test/unit/php/includes/tests/core/classes/class-test-rsvp.php
=> Get full coverage for Event Query and RSVP classes.

test/unit/php/includes/tests/core/classes/class-test-rsvp-setup.php
=> Added unit test for RSVP status method.

readme.md
=> Make ul list.

readme.md
=> Update bullet in readme to be more clear.

gatherpress.php, includes/data/credits.php, package-lock.json, package.json, readme.md
=> Prepping 0.32.0 release.

composer.json, composer.lock, includes/core/classes/class-event-setup.php, includes/core/classes/class-settings.php, includes/core/classes/class-venue.php, readme.md, test/unit/php/bootstrap.php
author was not added to supported for events and venues. This meant author was not showing up with changes to WordPress 6.8. 
Closes #1049 
Props @mauteri, @patriciabt
=> Add author to post type support for event and venue.

composer.json, composer.lock, includes/core/classes/class-event-setup.php, includes/core/classes/class-settings.php, includes/core/classes/class-venue.php, readme.md, test/unit/php/bootstrap.php
=> Get author issue into 0.32.1 branch.

composer.lock
=> Composer updates

composer.json, composer.lock
=> Fixed pmc-unit-test upstream and pointing to main branch again.

.github/workflows/sonarcloud.yml
=> Fix GH action.

includes/data/credits.php
=> Added new contributor to credits.

includes/core/classes/class-assets.php, src/blocks/event-date/edit.js, src/components/Timezone.js
* Fix issue with Event Date block not rendering on template pages.
* Adjust timezone array to only appear in editor.
Closes #923
Props @mauteri, @carstingaxion, @swissspidy
=> Limit rendering timezone array and fix event date block

.github/scripts/playground-preview/index.js, .github/scripts/wordpress-org-screenshots/blueprint.json, .wordpress-org/blueprints/blueprint.json
=> Fix demo data for 0.33.0.

.github/scripts/playground-preview/index.js
=> Remove multisite from playground (commented out).

includes/core/classes/blocks/class-dropdown.php, src/blocks/dropdown/block.json, src/blocks/dropdown/edit.js, src/blocks/dropdown/style.scss
Add to Calendar block (specifically the dropdown block) needs an increased z-index so it does not fall behind the venue block. Minimum setting is 1001. Z-index is completely adjustable in the block itself, but should set the default higher due to this issue.
Closes #
Props @mauteri
=> Fix z-index issue with Add to Calendar.

package-lock.json, package.json, src/components/OpenStreetMap.js
Fixes OSM/Leaflet issue when scrolling over the map and it zooming in.
Props @mauteri
=> Add gensture handling for leaflet.

.github/workflows/e2e-tests.yml, test/e2e/admin-tests/gatherpress-admin.spec.js, test/e2e/global-setup.js
=> Create artifacts directory in global-setup.js.

src/components/OpenStreetMap.js
=> Allow multiple venue blocks per event

.github/scripts/playground-preview/index.js, gatherpress.php
=> Update playground proxy and trigger run.

src/blocks/events-list/style.scss
=> Small adjustment to event list styling.

includes/templates/admin/emails/event-email.php
Closes #1073
> Fixed - Images should be added using wp_get_attachment_image() or similar functions
=> Use wp_get_attachment_image_src() to fix plugin-guidelines-issue

includes/core/classes/blocks/class-rsvp-response.php, includes/core/classes/class-rsvp-list-table.php, includes/core/classes/class-rsvp-query.php
Bug with missing filter for remove/add for RSVP exclusion in comment query. Fixed issues with counts. Fixed issue with "Mine" filter.
Closes #1131 
Props @mauteri, @carstingaxion
=> GP-1131: Fix RSVP view to only include RSVPs; Fix counts; Fix 'Mine' query.

docs/user/update-privacy-policy/README.md, includes/core/classes/class-setup.php, readme.md, test/unit/php/includes/tests/core/classes/class-test-setup.php
Closes #875
> Added a privacy policy content suggestion
=> Add a privacy policy content suggestion

.github/workflows/phpunit-tests.yml
Have unit tests run PHP 8.4.
Props @mauteri
=> Add 8.4 to PHPUnit testing matrix.

composer.lock
Follow-up for #1135
> Ooops, I forgot to update the composer dependencies in https://github.com/GatherPress/gatherpress/pull/1135, which I did locally to have the docs updated, but didn't push the updated composer.lock
>
> https://github.com/GatherPress/gatherpress/pull/1148#issuecomment-3150524014
This PR fixes this.
Closes #1148
> Fixed - Update dependencies to make use of the latest version of [akirk/extract-wp-hooks](https://github.com/akirk/extract-wp-hooks)
=> Update dependencies to make use of the latest version of akirk/extract-wp-hooks

includes/core/classes/class-autoloader.php
Replace hardcoded switch statement with automatic directory detection, allowing new class types to be added without modifying the autoloader code.
All classes still load via autoloader without fatal error.
Props @mauteri
=> Improve autoloader flexibility by removing hardcoded directory mappings.
